### ISSUE TITLE
Support Travis Enterprise

### ISSUE THREAD

**Issue by SimenB** [semantic-release/condition-travis#100]
See https://github.com/semantic-release/semantic-release/issues/540

I'd be happy to provide a PR for this 🙂

**Comment by SimenB** [comment]
BTW, have you tried emailing Travis about getting access to an enterprise instance for testing? I haven't mailed them before, but I'm hopeful they'd be positive towards helping with an integration for semantic-release.

https://docs.travis-ci.com/user/enterprise/#Trials-and-Licensing

**Comment by SimenB** [comment]
Anyways, I can test on Travis Enterprise as we use it at work. Ay ideas on where to start? I have no idea from where the call which fails even comes from.

(and I don't think I can remotely debug either, so it'll be push and see what happnes...)

**Comment by pvdlg** [comment]
The problem is actually in semantic-release/travis-deploy-once which use https://github.com/pwmckenna/node-travis-ci.
Unfortunately pwmckenna/node-travis-ci doesn't support Travis Enterprise. See [lib/travis-http.js#L5](https://github.com/pwmckenna/node-travis-ci/blob/master/lib/travis-http.js#L5).

In `condition-travis` we need to:
- Add a new config option `travisUrl` that can be configured via a plugin option or an environment variable. See `githubUrl ` in https://github.com/semantic-release/github for an example.
- Pass this url to https://github.com/semantic-release/travis-deploy-once

Then `semantic-release/travis-deploy-once` will have to make API calls with this url. There is multiple approach to achieve (by order of preference):
- Open a PR with https://github.com/pwmckenna/node-travis-ci to support an additional `travisUrl` parameter (that should be fairly easy to do, so I strongly favor this options)
- Replace `pwmckenna/node-travis-ci` by another lib that supports Travis Enterprise
- Implement all the API calls in `semantic-release/travis-deploy-once` with an http library like https://github.com/sindresorhus/got

We would gladly accept PRs on all that!

For now you can also set the environment variable `BUILD_LEADER_ID` to select on which job number `semantic-release` should run. By doing so the call to `semantic-release/travis-deploy-once` will be skipped and no API call will be made. See an example [here](https://github.com/semantic-release/condition-travis#using-travis-build-stages) (The build stage part is not required).

**Comment by pvdlg** [comment]
👍 It seems a PR would be welcomed to solve pwmckenna/node-travis-ci#21 :)

**Comment by SimenB** [comment]
PR sent. Not sure if it'll be released right away, though: https://github.com/pwmckenna/node-travis-ci/pull/19#issuecomment-346230739

**Comment by SimenB** [comment]
`BUILD_LEADER_ID` seems ignored - all 3 of my builds (node 8, 6, and 9) try to run semantic-release, and they all fail with the api error towards travis

**Comment by pvdlg** [comment]
That's quite surprising....The Node 6 job should exit right away due to https://github.com/semantic-release/semantic-release/blob/caribou/bin/semantic-release.js#L9

What value did you set for `BUILD_LEADER_ID` ?

**Comment by pvdlg** [comment]
Not if Travis allow to export variables like that. Can you set it in your `travis.yml` like that:
```yaml
env:
  - BUILD_LEADER_ID=1
```

**Comment by SimenB** [comment]
Oh sorry, I lied. Node 6 is not ran!

Relevant part of my .travis.yml:

```yml
language: node_js
node_js:
- 8
- 6
- 9
before_install:
- export NPM_TOKEN=""
script:
- yarn commitlint --from="$TRAVIS_BRANCH" --to="$TRAVIS_COMMIT"
- yarn commitlint --from=$TRAVIS_COMMIT
- yarn test
after_success: yarn semantic-release --debug
cache:
  yarn: true
branches:
  only:
  - master
env:
  global:
  - GITHUB_URL=https://github.schibsted.io
  - GITHUB_PREFIX=/api/v3
  - NPM_USERNAME=$ARTIFACTORY_USER
  - NPM_PASSWORD=$ARTIFACTORY_NPM_SECRET
  - NPM_EMAIL=$ARTIFACTORY_USER
  - BUILD_LEADER_ID=1
  - secure: some token
```
